/**
 * pdfnative-cli — the conformance corpus (PDF/A + PDF/X)
 * ========================================================
 * One table drives scripts/generate-pdfa-corpus.ts; `derived.pdfaCorpus` in
 * docs/assets/ecosystem.json is its length, `declared.pdfaSamples` and
 * `declared.pdfxSamples` the number of claiming files per standard.
 *
 * Every entry names the CLI invocation that produces it (`command` is the
 * human-readable manifest record, `run` performs it). Later entries may
 * consume earlier outputs (signed-/metadata-/pdfx4-signed reuse renders), so
 * the order matters and execution is sequential.
 *
 * Reproducibility: every render pins `--creation-date`, every signature
 * `--signing-time`, every metadata edit `--mod-date` to the instant in
 * scripts/helpers/io.ts, and the signing key is the committed test fixture
 * (tests/fixtures/rsa-key.pem) passed through the CHILD env only — so the
 * corpus bytes are stable across machines and the manifest's sha256 column
 * is diffable.
 *
 * Font embedding recipe: the CLI has no `embedFonts` switch — `--font latin`
 * registers the bundled Noto Sans loader and `--lang latin` injects the
 * matching `fontEntries`, which routes ALL Latin text away from non-embedded
 * base-14 Helvetica. Positive entries therefore render with
 * `--strict --font latin --lang latin` (strict mode turns any remaining
 * PDF/A diagnostic into a build failure before the first output byte).
 *
 * Negative canaries (`expectCompliant: false`) claim conformance but are
 * KNOWN non-conformant — the validator must reject them, otherwise the
 * validator itself is broken ("accepts everything") and the run fails.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { REPO_ROOT, TEST_OUTPUT_DIR, SAMPLE_CREATION_ISO } from '../helpers/io.js';

export const OUT_DIR = join(TEST_OUTPUT_DIR, 'pdfa');
export const SPECS_DIR = join(OUT_DIR, '.specs');
const SAMPLES = join(REPO_ROOT, 'samples', 'render');
const FIXTURES = join(REPO_ROOT, 'tests', 'fixtures');

export type Claim = 'pdfa' | 'pdfx' | 'none';

export interface CorpusEntry {
    readonly file: string;
    readonly command: string;
    /** Which standard the output claims in its XMP. */
    readonly claims: Claim;
    /** Default true; false marks a negative canary. Ignored for `claims: 'none'`. */
    readonly expectCompliant?: boolean;
    /** CLI argv for the invocation (the generator spawns dist/cli.cjs). */
    readonly args: (out: (file: string) => string) => readonly string[];
    /** Extra child environment (signing material travels this way). */
    readonly env?: () => Readonly<Record<string, string>>;
    /** Anything to write before the invocation (spec fixtures under .specs/). */
    readonly before?: () => void;
}

const pdfaSample = (name: string): string => join(SAMPLES, 'pdfa', name);
const PINNED = ['--creation-date', SAMPLE_CREATION_ISO] as const;
/** The embedding recipe every positive entry uses (see the header comment). */
const STRICT_FONTS = ['--strict', '--font', 'latin', '--lang', 'latin'] as const;

/** The exact attachment recipe from the samples table (absolute payload path). */
const ATTACHMENT_FLAGS = [
    '--tagged', 'pdfa3b',
    '--attachment', `${join(SAMPLES, 'attachments', 'invoice.xml')}:application/xml:Source:Structured invoice payload`,
] as const;

/** PDF/X-4 recipe: the synthetic prtr CMYK profile shipped with the samples. */
const PDFX_FLAGS = [
    '--pdfx', 'pdfx4',
    '--output-intent-icc', join(SAMPLES, 'print', 'synthetic-cmyk.icc'),
    '--output-intent-id', 'Synthetic CMYK (pdfnative test profile)',
    '--trapped', 'false',
] as const;

/**
 * Minimal PdfParams fixture for the table variant. The table variant requires
 * the full ledger shape (docTitle / infoItems / balanceText / countText /
 * footerText alongside title / headers / rows) — see
 * samples/render/table-variant/01-financial-transactions.json.
 */
const TABLE_SPEC = {
    docTitle: 'Corpus — table variant under PDF/A',
    title: 'Corpus table',
    infoItems: [],
    balanceText: '',
    countText: '',
    headers: ['Item', 'Qty', 'Price'],
    rows: [
        { type: 'data', pointed: false, cells: ['Widget', '2', '9.99'] },
        { type: 'data', pointed: false, cells: ['Gadget', '1', '24.50'] },
    ],
    footerText: 'Generated by scripts/generate-pdfa-corpus.ts',
};

/** A square annotation inside the print area: PDF/X forbids it (validatePdfX must reject). */
const BAD_ANNOTATION_SPEC = [
    { page: 1, type: 'square', rect: [72, 640, 300, 700], color: '#ff0000', contents: 'Not allowed under PDF/X' },
];

function writeSpec(name: string, value: unknown): string {
    mkdirSync(SPECS_DIR, { recursive: true });
    const spec = join(SPECS_DIR, name);
    writeFileSync(spec, `${JSON.stringify(value, null, 2)}\n`);
    return spec;
}

function signingEnv(): Readonly<Record<string, string>> {
    return {
        PDFNATIVE_SIGN_KEY: readFileSync(join(FIXTURES, 'rsa-key.pem'), 'utf8'),
        PDFNATIVE_SIGN_CERT: readFileSync(join(FIXTURES, 'rsa-cert.pem'), 'utf8'),
    };
}

export const CORPUS: readonly CorpusEntry[] = [
    // ── PDF/A positives: --strict --font latin --lang latin ─────────────
    {
        file: 'sample-pdfa1b.pdf', claims: 'pdfa',
        command: 'render samples/render/pdfa/01-pdfa-1b.json --strict --font latin --lang latin',
        args: (out) => ['render', '--input', pdfaSample('01-pdfa-1b.json'), '--output', out('sample-pdfa1b.pdf'), ...STRICT_FONTS, ...PINNED],
    },
    {
        file: 'sample-pdfa2b.pdf', claims: 'pdfa',
        command: 'render samples/render/pdfa/02-pdfa-2b.json --strict --font latin --lang latin',
        args: (out) => ['render', '--input', pdfaSample('02-pdfa-2b.json'), '--output', out('sample-pdfa2b.pdf'), ...STRICT_FONTS, ...PINNED],
    },
    {
        file: 'sample-pdfa3b.pdf', claims: 'pdfa',
        command: 'render samples/render/pdfa/03-pdfa-3b.json --strict --font latin --lang latin',
        args: (out) => ['render', '--input', pdfaSample('03-pdfa-3b.json'), '--output', out('sample-pdfa3b.pdf'), ...STRICT_FONTS, ...PINNED],
    },
    {
        file: 'sample-pdfa2u.pdf', claims: 'pdfa',
        command: 'render samples/render/pdfa/04-pdfa-2u.json --strict --font latin --lang latin',
        args: (out) => ['render', '--input', pdfaSample('04-pdfa-2u.json'), '--output', out('sample-pdfa2u.pdf'), ...STRICT_FONTS, ...PINNED],
    },
    {
        // PDF/A-3b with an /AFRelationship Source XML payload (Factur-X pattern).
        file: 'attachment-pdfa3b-xml.pdf', claims: 'pdfa',
        command: 'render samples/render/attachments/01-pdfa3-with-xml.json --tagged pdfa3b --attachment invoice.xml:application/xml:Source:Structured invoice payload --strict --font latin --lang latin',
        args: (out) => ['render', '--input', join(SAMPLES, 'attachments', '01-pdfa3-with-xml.json'), '--output', out('attachment-pdfa3b-xml.pdf'), ...ATTACHMENT_FLAGS, ...STRICT_FONTS, ...PINNED],
    },
    {
        file: 'headers-footers-pdfa2b.pdf', claims: 'pdfa',
        command: 'render samples/render/pdfa/02-pdfa-2b.json --header-left "{title}" --footer-center "Page {page} of {pages}" --strict --font latin --lang latin',
        args: (out) => ['render', '--input', pdfaSample('02-pdfa-2b.json'), '--output', out('headers-footers-pdfa2b.pdf'), '--header-left', '{title}', '--footer-center', 'Page {page} of {pages}', ...STRICT_FONTS, ...PINNED],
    },
    {
        file: 'outline-pdfa2b.pdf', claims: 'pdfa',
        command: 'render samples/render/pdfa/02-pdfa-2b.json --outline auto --strict --font latin --lang latin',
        args: (out) => ['render', '--input', pdfaSample('02-pdfa-2b.json'), '--output', out('outline-pdfa2b.pdf'), '--outline', 'auto', ...STRICT_FONTS, ...PINNED],
    },
    {
        // Opacity 1: PDF/A-1 forbids transparency and PDF/A-2 constrains it;
        // a fully opaque watermark keeps the claim safe at every level.
        file: 'watermark-pdfa2b.pdf', claims: 'pdfa',
        command: 'render samples/render/pdfa/02-pdfa-2b.json --watermark-text DRAFT --watermark-opacity 1 --strict --font latin --lang latin',
        args: (out) => ['render', '--input', pdfaSample('02-pdfa-2b.json'), '--output', out('watermark-pdfa2b.pdf'), '--watermark-text', 'DRAFT', '--watermark-opacity', '1', ...STRICT_FONTS, ...PINNED],
    },
    {
        // PAdES baseline-B signature over the PDF/A-2b render, via an
        // incremental update (the claim must survive). Credentials travel
        // through the CHILD env only (never disk beyond the fixture, never
        // the parent env). RSA PKCS#1 v1.5 is deterministic.
        file: 'signed-pdfa2b.pdf', claims: 'pdfa',
        command: 'sign sample-pdfa2b.pdf --profile pades --signing-time <pinned> (test fixture RSA-2048 via env)',
        args: (out) => ['sign', '--input', out('sample-pdfa2b.pdf'), '--output', out('signed-pdfa2b.pdf'), '--profile', 'pades', '--signing-time', SAMPLE_CREATION_ISO],
        env: signingEnv,
    },
    {
        // Incremental /Info + XMP rewrite on a claiming file: the PDF/A-2u
        // claim and metadata synchronisation (ISO 19005 6.6.2) must survive.
        file: 'metadata-pdfa2u.pdf', claims: 'pdfa',
        command: 'metadata sample-pdfa2u.pdf --title "Corpus metadata check" --author "pdfnative-cli corpus" --mod-date <pinned>',
        args: (out) => ['metadata', '--input', out('sample-pdfa2u.pdf'), '--title', 'Corpus metadata check', '--author', 'pdfnative-cli corpus', '--mod-date', SAMPLE_CREATION_ISO, '-o', out('metadata-pdfa2u.pdf')],
    },
    {
        // v1.5.0: the table variant embeds fonts too (`--lang` merges
        // fontEntries on the PdfParams path), so it can claim PDF/A.
        file: 'table-pdfa2b-fonts.pdf', claims: 'pdfa',
        command: 'render .specs/table.json --variant table --tagged pdfa2b --strict --font latin --lang latin',
        before: () => { writeSpec('table.json', TABLE_SPEC); },
        args: (out) => ['render', '--input', join(SPECS_DIR, 'table.json'), '--output', out('table-pdfa2b-fonts.pdf'), '--variant', 'table', '--tagged', 'pdfa2b', ...STRICT_FONTS, ...PINNED],
    },

    // ── PDF/A negative canaries: rendered WITHOUT --strict and WITHOUT fonts ─
    {
        // Base-14 Helvetica is referenced, not embedded: the file claims
        // PDF/A-2b but violates ISO 19005-2 §6.2.11.4.1. veraPDF MUST reject it.
        file: 'nofonts-pdfa2b.pdf', claims: 'pdfa', expectCompliant: false,
        command: 'render samples/render/pdfa/02-pdfa-2b.json (no --strict, no fonts — ISO 19005-2 6.2.11.4.1 canary)',
        args: (out) => ['render', '--input', pdfaSample('02-pdfa-2b.json'), '--output', out('nofonts-pdfa2b.pdf'), ...PINNED],
    },
    {
        // Table variant under PDF/A-1b without --font: Helvetica stays
        // non-embedded and the claim violates ISO 19005-1 §6.3.4.
        file: 'table-pdfa1b-nofonts.pdf', claims: 'pdfa', expectCompliant: false,
        command: 'render .specs/table.json --variant table --tagged pdfa1b (no fonts — ISO 19005-1 6.3.4 canary)',
        before: () => { writeSpec('table.json', TABLE_SPEC); },
        args: (out) => ['render', '--input', join(SPECS_DIR, 'table.json'), '--output', out('table-pdfa1b-nofonts.pdf'), '--variant', 'table', '--tagged', 'pdfa1b', ...PINNED],
    },

    // ── PDF/X-4 (v1.5.0): validated by pdfnative's validatePdfX(), not veraPDF ─
    {
        file: 'pdfx4-print.pdf', claims: 'pdfx',
        command: 'render samples/render/print/05-pdfx4.json --pdfx pdfx4 --output-intent-icc synthetic-cmyk.icc --trapped false --strict --font latin --lang latin',
        args: (out) => ['render', '--input', join(SAMPLES, 'print', '05-pdfx4.json'), '--output', out('pdfx4-print.pdf'), ...PDFX_FLAGS, ...STRICT_FONTS, ...PINNED],
    },
    {
        // A PAdES signature is an incremental update; the PDF/X-4 claim, the
        // OutputIntent and the embedded fonts must survive it.
        file: 'pdfx4-signed.pdf', claims: 'pdfx',
        command: 'sign pdfx4-print.pdf --profile pades --signing-time <pinned>',
        args: (out) => ['sign', '--input', out('pdfx4-print.pdf'), '--output', out('pdfx4-signed.pdf'), '--profile', 'pades', '--signing-time', SAMPLE_CREATION_ISO],
        env: signingEnv,
    },
    {
        // Negative canary: a markup annotation inside the print area on a
        // claiming file. ISO 15930-7 forbids it; validatePdfX MUST reject.
        file: 'pdfx4-bad-annotation.pdf', claims: 'pdfx', expectCompliant: false,
        command: 'annotate pdfx4-print.pdf --annotations .specs/bad-annotation.json (annotation in the print area — ISO 15930-7 canary)',
        before: () => { writeSpec('bad-annotation.json', BAD_ANNOTATION_SPEC); },
        args: (out) => ['annotate', '--input', out('pdfx4-print.pdf'), '--output', out('pdfx4-bad-annotation.pdf'), '--annotations', join(SPECS_DIR, 'bad-annotation.json')],
    },
];

/** Number of entries claiming a given standard — the coverage canaries' expectation. */
export function claimingCount(claim: Claim): number {
    return CORPUS.filter((e) => e.claims === claim).length;
}
