# render/print/06-gray-pdfx4.ps1 — PDF/X-4 under a Gray output intent (v1.5.0)
#
# pdfnative 1.8.0 accepts RGB, CMYK and Gray output profiles. synthetic-gray.icc is a
# valid monochrome prtr profile generated by scripts/lib/synthetic-gray-profile.ts -
# not a press condition: ask your printer for theirs.
#
# Prerequisites:
#   - pdfnative-cli installed globally: npm install -g pdfnative-cli
#
# Usage:
#   pwsh samples/render/print/06-gray-pdfx4.ps1

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir   = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $ScriptDir))
$OutputDir = Join-Path $RootDir 'samples\output\print'
New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

Write-Host '→ Rendering a one-ink PDF/X-4 file'
& pdfnative render --input (Join-Path $ScriptDir '06-gray-pdfx4.json') --output (Join-Path $OutputDir '06-gray-pdfx4.pdf') --pdfx pdfx4 --output-intent-icc (Join-Path $ScriptDir 'synthetic-gray.icc') --output-intent-id 'Synthetic Gray (pdfnative-cli test profile)' --trapped false --font latin --lang latin --strict --creation-date 2026-01-01T00:00:00Z
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
Write-Host '→ Asserting the claim'
& pdfnative inspect --input (Join-Path $OutputDir '06-gray-pdfx4.pdf') --check pdfx
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
Write-Host '→ CMYK content contradicts a Gray intent: --strict refuses it (PDFX_DEVICE_CMYK)'
& pdfnative render --input (Join-Path $ScriptDir '03-cmyk-colours.json') --output (Join-Path $OutputDir '06-gray-cmyk-refused.pdf') --pdfx pdfx4 --output-intent-icc (Join-Path $ScriptDir 'synthetic-gray.icc') --trapped false --font latin --lang latin --strict
if ($LASTEXITCODE -eq 0) { Write-Host '  ✗ expected a refusal'; exit 1 }
Write-Host '  ✓ refused, as expected'
Write-Host "✓ Done: $OutputDir"
exit 0
