#!/usr/bin/env bash
# render/print/06-gray-pdfx4.sh — PDF/X-4 under a Gray output intent (v1.5.0)
#
# pdfnative 1.8.0 accepts RGB, CMYK and Gray output profiles. synthetic-gray.icc is a
# valid monochrome prtr profile generated by scripts/lib/synthetic-gray-profile.ts -
# not a press condition: ask your printer for theirs.
#
# Prerequisites:
#   - pdfnative-cli installed globally: npm install -g pdfnative-cli
#
# Usage:
#   bash samples/render/print/06-gray-pdfx4.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/samples/output/print"
mkdir -p "$OUTPUT_DIR"

echo "→ Rendering a one-ink PDF/X-4 file"
pdfnative render --input "$SCRIPT_DIR/06-gray-pdfx4.json" --output "$OUTPUT_DIR/06-gray-pdfx4.pdf" --pdfx pdfx4 --output-intent-icc "$SCRIPT_DIR/synthetic-gray.icc" --output-intent-id "Synthetic Gray (pdfnative-cli test profile)" --trapped false --font latin --lang latin --strict --creation-date 2026-01-01T00:00:00Z
echo "→ Asserting the claim"
pdfnative inspect --input "$OUTPUT_DIR/06-gray-pdfx4.pdf" --check pdfx
echo "→ CMYK content contradicts a Gray intent: --strict refuses it (PDFX_DEVICE_CMYK)"
if pdfnative render --input "$SCRIPT_DIR/03-cmyk-colours.json" --output "$OUTPUT_DIR/06-gray-cmyk-refused.pdf" --pdfx pdfx4 --output-intent-icc "$SCRIPT_DIR/synthetic-gray.icc" --trapped false --font latin --lang latin --strict; then
  echo "  ✗ expected a refusal"
  exit 1
else
  echo "  ✓ refused, as expected"
fi
echo "✓ Done: $OUTPUT_DIR"
